
export const ADD_TODO = 'ADD_TODO';
export const REQUEST_TODOS = 'REQUEST_TODOS';
export const REQUEST_TODOS_SUCCESS = 'REQUEST_TODOS_SUCCESS';
export const REQUEST_TODOS_FAILURE = 'REQUEST_TODOS_FAILURE';
export const SET_TODOS_SEARCH_TEXT = 'SET_TODOS_SEARCH_TEXT';